### ISSUE TITLE
Positioning on Install

### ISSUE THREAD

**Issue by damassi** [damassi/atom-scroll-percentage#2]
When you first install the package there are some layout issues that require a refresh or a restart. Need to find a way to ensure that the package is positioned within a postInstall callback.

**Comment by tonatiuh** [comment]
I installed it along with the material-ui theme and the percentage didn't appear. Just FYI.

**Comment by damassi** [comment]
@tonatiuh - When you restart Atom does it appear? I just installed using Material theme and everything appears well.  

<img width="660" alt="screen shot 2016-02-28 at 2 36 34 pm" src="https://cloud.githubusercontent.com/assets/236943/13382402/b006f7c2-de28-11e5-814a-e032233cd04d.png">

**Comment by damassi** [comment]
I adjusted the styles a bit so let me know if you're still seeing anything. Latest should be published.

**Comment by tonatiuh** [comment]
Hmm, weird, I see 0% always now. Probably that may be because of a conflict with another plugin. If I have the chance I'll check and report what I found.

**Comment by damassi** [comment]
Oops! that's actually a bug. If there is not enough content to trigger a scroll, rather than 0% it should be 100%. Will fix.

**Comment by tonatiuh** [comment]
Hey, I just found what is the issue on my local with this plugin, I have installed the vim-mode package, and when I navigate using the j or the k keys the scroll indicator isn't updated. I'm going to create an issue about this, so that it's documented.

**Comment by tonatiuh** [comment]
Done https://github.com/damassi/atom-scroll-percentage/issues/4.
